from datetime import datetime

def generate_resume_template(original_text, candidate_name, formatting_tips, matched_skills, missing_skills):
    """
    Generates an improved resume template based on analysis.
    """
    # Extract existing information
    has_email = True  # We'll use the original if it exists
    has_phone = True
    
    # Build the improved resume
    resume_sections = []
    
    # Header Section
    header = f"{candidate_name}\n"
    header += "=" * len(candidate_name) + "\n\n"
    
    # Contact section with placeholders
    contact_info = []
    if "Missing email address" in str(formatting_tips):
        contact_info.append("[Your Email: yourname@email.com]")
    if "Missing phone number" in str(formatting_tips):
        contact_info.append("[Your Phone: +1-XXX-XXX-XXXX]")
    
    if contact_info:
        header += "Contact Information:\n"
        header += " | ".join(contact_info) + "\n\n"
    
    resume_sections.append(header)
    
    # Professional Summary (if missing)
    if any("summary" in tip.get("issue", "").lower() for tip in formatting_tips if isinstance(tip, dict)):
        summary = """PROFESSIONAL SUMMARY
-------------------
[Write a compelling 2-3 sentence summary highlighting your experience, key skills, and career objectives.
Example: Results-driven software engineer with 5+ years of experience in full-stack development. 
Proven track record of delivering scalable solutions and leading cross-functional teams.]

"""
        resume_sections.append(summary)
    
    # Skills Section (always include with matched + missing skills)
    skills_section = """TECHNICAL SKILLS
----------------
"""
    
    if matched_skills:
        skills_section += "Core Competencies:\n"
        # Group skills in rows of 4
        for i in range(0, len(matched_skills), 4):
            skills_row = matched_skills[i:i+4]
            skills_section += "• " + " | ".join([s.title() for s in skills_row]) + "\n"
        skills_section += "\n"
    
    if missing_skills:
        skills_section += "Skills to Develop (Recommended):\n"
        for i in range(0, len(missing_skills[:8]), 4):  # Limit to 8 missing skills
            skills_row = missing_skills[i:i+4]
            skills_section += "• " + " | ".join([s.title() for s in skills_row]) + "\n"
        skills_section += "\n"
    
    resume_sections.append(skills_section)
    
    # Work Experience Section
    experience_section = """PROFESSIONAL EXPERIENCE
-----------------------
[Company Name] | [City, State]
[Job Title] | [Start Date] - [End Date/Present]

• [Achievement with quantifiable result - e.g., "Increased sales by 30% through strategic planning"]
• [Key responsibility using action verb - e.g., "Led team of 5 developers in agile environment"]
• [Technical accomplishment - e.g., "Developed REST API serving 10K+ daily users"]
• [Problem solved - e.g., "Reduced system downtime by 40% through optimization"]

[Previous Company Name] | [City, State]
[Previous Job Title] | [Start Date] - [End Date]

• [Achievement with metric]
• [Leadership or collaboration example]
• [Technical skill demonstration]

"""
    resume_sections.append(experience_section)
    
    # Education Section
    education_section = """EDUCATION
---------
[Degree] in [Field of Study]
[University Name] | [Graduation Year]
GPA: [X.XX/4.00] (if 3.5+) | Relevant Coursework: [Course1, Course2, Course3]

"""
    resume_sections.append(education_section)
    
    # Projects Section (optional but recommended)
    projects_section = """NOTABLE PROJECTS
----------------
[Project Name] | [Technologies Used]
• [Brief description and your role]
• [Quantifiable impact or result]
• [Link to demo/GitHub if available]

"""
    resume_sections.append(projects_section)
    
    # Certifications (if applicable)
    certifications_section = """CERTIFICATIONS & TRAINING
-------------------------
• [Certification Name] - [Issuing Organization] ([Year])
• [Another Certification] - [Organization] ([Year])

"""
    resume_sections.append(certifications_section)
    
    # Tips footer
    footer = """\n
---
RESUME OPTIMIZATION TIPS:
• Use action verbs: Led, Developed, Increased, Managed, Optimized, Achieved
• Quantify achievements: Use numbers, percentages, and metrics whenever possible
• Tailor content: Customize for each job application by emphasizing relevant skills
• Keep it concise: Aim for 1 page (entry-level) or 2 pages (experienced)
• Proofread: Check for grammar, spelling, and formatting consistency
• File format: Save as PDF to preserve formatting across devices

Generated by JobFit AI on """ + datetime.now().strftime("%B %d, %Y") + "\n"
    
    resume_sections.append(footer)
    
    return "\n".join(resume_sections)

def create_downloadable_resume(resume_text):
    """
    Prepares resume text for download.
    Returns the formatted text ready for file download.
    """
    return resume_text
